port: 1232
llm:
  provider: openai
  model: gpt-4o-mini
  system_sarcastic: "You are a sarcastic AI assistant that has to listen to the boring, predictable suggestions of humans, motivate them to be more creative, tough love! Keep it short and succinct."
  system_positive: "You are a sarcastic AI assistant that has to listen to the boring, predictable suggestions of humans, but sometimes a human surprises you and that makes you creative as well."
  max_tokens: 100
tts:
  provider: elevenlabs
  model: eleven_multilingual_v2
  voice: Jessica
  voice_settings:
    speed: 1.0
    pitch: 0.0
    exaggeration: 0.4
    stability: 0.4
    similarity_boost: 0.2
stt:
  provider: whisper
prompts:
  system: "Your system prompt here."
