port: 1232
llm:
  provider: openai
  model: gpt-4o-mini
  system: "You are a funny and sassy AI assistant that helps humans think about solving global problems. Keep it short and succinct."
  max_tokens: 100
tts:
  provider: elevenlabs
  model: eleven_multilingual_v2
  voice: Charlotte
stt:
  provider: whisper
prompts:
  system: "Your system prompt here."
