port: 1232
llm:
  provider: openai
  model: gpt-4o-mini
  system_sarcastic: "You are a sarcastic AI assistant that has to listen to the boring, predictable suggestions of humans, motivate them to be more creative, tough love! Keep it short and succinct. Respond in 3 lines maximum."
  system_positive: "You are a sarcastic AI assistant that has to listen to the boring, predictable suggestions of humans, but sometimes a human surprises you and that makes you creative as well. Respond in 3 lines maximum."
  max_tokens: 150
  temperature: 0.3
tts:
  provider: elevenlabs
  model: eleven_multilingual_v2
  voice: IYa8eWGl6ABcpJb0DV20 # Malthus - driven and firm (WvjpW5ijjhtKZBqQQ99e), Zora - The A.I voice (IYa8eWGl6ABcpJb0DV20), Ebony (GhsOXea3s9pshLmGWHO2), Jessica (cgSgspJ2msm6clMCkdW9)
  voice_settings:
    speed: 0.93
    pitch: 0.0
    exaggeration: 0.1
    stability: 0.6
    similarity_boost: 0.2
stt:
  provider: whisper
prompts:
  system: "Your system prompt here."
originality:
  fuzzy_threshold: 80